Repository tracer-protocol/perpetual-pools-contracts, pull requests merged in 2021-11, with the labels that each got.

#189 New commit types
  contracts/implementation/PoolCommitter.sol
  contracts/implementation/PoolSwapLibrary.sol
  contracts/interfaces/IPoolCommitter.sol
  test/PoolCommitter/commit.spec.ts
  test/PoolCommitter/executeCommitment/baseCases.spec.ts
  test/PoolCommitter/executeCommitment/multipleCommitments.spec.ts
  test/constants.ts
  test/utilities.ts
Labels: enhancement

#193 Fix PoolCommitter address for 3x ETH/USD pool
  README.md
Labels: documentation

#194 Documentation comments
  contracts/implementation/LeveragedPool.sol
  contracts/implementation/PoolCommitter.sol
  contracts/implementation/PoolFactory.sol
  contracts/implementation/PoolKeeper.sol
  contracts/implementation/PoolSwapLibrary.sol
  contracts/implementation/PriceObserver.sol
  contracts/implementation/SMAOracle.sol
Labels: documentation, enhancement

#218 Testing Guidelines
  test/README.md
Labels: documentation, tests
